version: "3.3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - strapi
      - frontend
    restart: always # because it is routing traffic to our entire app
    ports:
      - 80:80
      - 443:443
  strapi:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app/srv/app
    ports:
      - '1337:1337'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    depends_on:
      - strapi
