version: "3.8"

services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo
    networks:
      - sos-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    networks:
      - sos-network
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./strapidata:/data/db
    networks:
      - sos-network

networks:
  sos-network:
    driver: bridge

volumes:
  strapidata:
